
---
- name: Install PostgreSQL and its dependencies
  yum:
    name:
      - postgresql
      - postgresql-server
      - postgresql-contrib
    state: present

- name: Ensure PostgreSQL service is running
  systemd:
    name: postgresql
    state: started
    enabled: yes

- name: Create database
  postgresql_db:
    name: devopsdb
    state: present
    login_user: postgres
    login_password: password  # Make sure this is correct
    login_host: "172.31.22.138"  # This should be the IP address

- name: Create database user
  postgresql_user:
    name: devops
    password: password  # Update with the desired password
    state: present
    login_user: postgres
    login_password: password  # Ensure this is also correct
    login_host: "172.31.22.138"  # This should be the IP address  

- name: Create database user
  postgresql_user:
    name: devops
    password: password  # Update with the desired password
    state: present
    login_user: postgres
    login_password: password  # Ensure this is also correct
    login_host: "172.31.22.138"

    
