---
- name: Install Python and pip
  yum:
    name:
      - python3
      - python3-pip
    state: present
- name: Ensure pip is up-to-date
  pip:
    name: pip
    state: latest
    executable: pip3
- name: Install Flask
  pip:
    name: flask
    executable: pip3
