---
- name: Create app directory
  file:
    path: /opt/flask_app
    state: directory
- name: Copy artifact to target
  copy:
    src: "../../artifacts/{{ artifact_name }}"
    dest: /opt/flask_app/
- name: Extract app
  unarchive:
    src: /opt/flask_app/{{ artifact_name }}
    dest: /opt/flask_app
    remote_src: yes
