---
- name: Create app directory
  file:
    path: /opt/flask_app
    state: directory
  become: yes

- name: Copy app artifact
  copy:
    src: "{{ artifact_path }}"
    dest: /opt/flask_app/app.tar.gz
  become: yes

- name: Extract app artifact
  unarchive:
    src: /opt/flask_app/app.tar.gz
    dest: /opt/flask_app
    remote_src: yes
  become: yes
