---
- name: Deploy PostgreSQL on DB server
  hosts: db_servers
  roles:
    - postgresql

- name: Deploy Flask app on app servers
  hosts: app_servers
  vars:
    artifact_path: "/var/lib/jenkins/workspace/flask-app-cicd/app.tar.gz"
    db_host: "172.31.23.25"
  roles:
    - python_flask
    - copy_app
    - connect_db
