---
- hosts: appservers
  become: yes
  tasks:
    - name: Ensure python3-dnf is installed
      dnf:
        name: python3-dnf
        state: present

    - name: Ensure python3-requests is installed
      dnf:
        name: python3-requests
        state: present

  roles:
    - configure_app
    - setup_postgres








