---
- name: Install PostgreSQL
  yum:
    name:
      - postgresql
    state: present
  become: yes

- name: Initialize PostgreSQL
  command: postgresql-setup initdb
  args:
    creates: /var/lib/pgsql/data/postgresql.conf
  become: yes

- name: Start and enable PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes
  become: yes

- name: Copy database initialization script
  copy:
    src: ../../database/init.sql
    dest: /tmp/init.sql
  become: yes

- name: Initialize database
  shell: psql -f /tmp/init.sql
  become: yes
  become_user: postgres
